/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-10-09 10:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.busbooking.filter.CsrfTokenFilter;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.busbooking.filter.CsrfTokenFilter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<header class=\"header\">\n");
      out.write("    <div class=\"header-left\">\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo(1).png\" alt=\"logo\" class=\"header-left__logo\" />\n");
      out.write("\n");
      out.write("        <svg\n");
      out.write("            class=\"menu-header__icon\"\n");
      out.write("            xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("            viewBox=\"0 0 640 640\"\n");
      out.write("        >\n");
      out.write("            <path\n");
      out.write("                d=\"M96 160C96 142.3 110.3 128 128 128L512 128C529.7 128 544 142.3 544 160C544 177.7 529.7 192 512 192L128 192C110.3 192 96 177.7 96 160zM96 320C96 302.3 110.3 288 128 288L512 288C529.7 288 544 302.3 544 320C544 337.7 529.7 352 512 352L128 352C110.3 352 96 337.7 96 320zM544 480C544 497.7 529.7 512 512 512L128 512C110.3 512 96 497.7 96 480C96 462.3 110.3 448 128 448L512 448C529.7 448 544 462.3 544 480z\"\n");
      out.write("            />\n");
      out.write("        </svg>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"header-right\">\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"header-account\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/IMG_4612.jpg\" alt=\"avatar\" class=\"header-account__avatar\" />\n");
      out.write("\n");
      out.write("                <label for=\"dropdown\">\n");
      out.write("                    <svg\n");
      out.write("                        class=\"header-account__dropdown-icon\"\n");
      out.write("                        xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("                        viewBox=\"0 0 640 640\"\n");
      out.write("                    >\n");
      out.write("                        <path\n");
      out.write("                            d=\"M480 224C492.9 224 504.6 231.8 509.6 243.8C514.6 255.8 511.8 269.5 502.7 278.7L342.7 438.7C330.2 451.2 309.9 451.2 297.4 438.7L137.4 278.7C128.2 269.5 125.5 255.8 130.5 243.8C135.5 231.8 147.1 224 160 224L480 224z\"\n");
      out.write("                        />\n");
      out.write("                    </svg>\n");
      out.write("                </label>\n");
      out.write("                <input\n");
      out.write("                    type=\"checkbox\"\n");
      out.write("                    name=\"dropdown\"\n");
      out.write("                    id=\"dropdown\"\n");
      out.write("                    class=\"dropdown-checkbox\"\n");
      out.write("                />\n");
      out.write("                <div class=\"dropdown\">\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li class=\"dropdown-item\">Profile</li>\n");
      out.write("                        <li class=\"dropdown-item\">Settings</li>\n");
      out.write("                        \n");
      out.write("                        <!-- === NÂNG CẤP BẢO MẬT: Chuyển link logout thành form === -->\n");
      out.write("                        <li class=\"dropdown-item\">\n");
      out.write("                            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" method=\"post\" style=\"display: inline;\">\n");
      out.write("                                <!-- Thêm token bí mật vào form -->\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print( CsrfTokenFilter.CSRF_TOKEN_SESSION_ATTR );
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.csrfToken}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                                <button type=\"submit\" class=\"logout-button\">Logout</button>\n");
      out.write("                            </form>\n");
      out.write("                        </li>\n");
      out.write("                        <!-- === KẾT THÚC NÂNG CẤP === -->\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <p class=\"header-account__name\">Tien Dat</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    .logout-button {\n");
      out.write("        background: none;\n");
      out.write("        border: none;\n");
      out.write("        padding: 0;\n");
      out.write("        margin: 0;\n");
      out.write("        font: inherit;\n");
      out.write("        color: inherit;\n");
      out.write("        cursor: pointer;\n");
      out.write("        text-align: left;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("    .logout-button:hover {\n");
      out.write("        /* Bạn có thể thêm hiệu ứng hover ở đây nếu muốn */\n");
      out.write("        text-decoration: underline;\n");
      out.write("    }\n");
      out.write("</style>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
