/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-19 23:25:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<aside class=\"sidebar\">\n");
      out.write("    <ul class=\"sidebar-list\">\n");
      out.write("        <!-- Dashboard -->\n");
      out.write("        <li class=\"sidebar-item\" data-page=\"dashboard\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page?view=dashboard\">\n");
      out.write("                <svg class=\"sidebar-item__icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("                    <path d=\"M304 70.1C313.1...\"/>\n");
      out.write("                </svg>\n");
      out.write("                <span class=\"text\">Dashboard</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <!-- Quản lý tài xế -->\n");
      out.write("        <li class=\"sidebar-item\" data-page=\"drivers\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drivers?action=list\">\n");
      out.write("                <svg class=\"sidebar-item__icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("                    <path d=\"M376 88C376...\"/>\n");
      out.write("                </svg>\n");
      out.write("                <span class=\"text\">Quản lý tài xế</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <!-- Quản lý xe -->\n");
      out.write("        <li class=\"sidebar-item\" data-page=\"buses\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/buses?action=list\">\n");
      out.write("                <svg class=\"sidebar-item__icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("                    <path d=\"M192 64C139...\"/>\n");
      out.write("                </svg>\n");
      out.write("                <span class=\"text\">Quản lý xe</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <!-- Quản lý chuyến -->\n");
      out.write("        <li class=\"sidebar-item\" data-page=\"trips\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/trips?action=list\">\n");
      out.write("                <svg class=\"sidebar-item__icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("                    <path d=\"M576 112C576...\"/>\n");
      out.write("                </svg>\n");
      out.write("                <span class=\"text\">Quản lý chuyến</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <!-- Tài khoản -->\n");
      out.write("        <li class=\"sidebar-item\" data-page=\"accounts\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accounts?action=list\">\n");
      out.write("                <svg class=\"sidebar-item__icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("                    <path d=\"M576 112C576...\"/>\n");
      out.write("                </svg>\n");
      out.write("                <span class=\"text\">Tài khoản</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <!-- Dữ liệu -->\n");
      out.write("        <li class=\"sidebar-item\" data-page=\"datas\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/datas?action=list\">\n");
      out.write("                <svg class=\"sidebar-item__icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 640 640\">\n");
      out.write("                    <path d=\"M576 112C576...\"/>\n");
      out.write("                </svg>\n");
      out.write("                <span class=\"text\">Dữ liệu</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("</aside>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
